### ISSUE TITLE
Calculation issues

### ISSUE THREAD

**Issue by pgsengstock** [monotok/zabbix-template-freenas11#1]
I have several datasets and pools that are well over 100TB, but none seem to register higher than a 4-6TB in total.  There is clearly some major calculation issue somewhere, but it's not consistent amongst the datasets.  Any suggestions on the best place to start digging to fix up the template accordingly?  Thanks!

![screen shot 2018-09-27 at 11 49 19 am](https://user-images.githubusercontent.com/6633715/46161766-0ad78680-c24c-11e8-95a5-2b9c8c9295f8.png)
![screen shot 2018-09-27 at 11 49 46 am](https://user-images.githubusercontent.com/6633715/46161767-0ad78680-c24c-11e8-9bf8-b559f7f39038.png)
![screen shot 2018-09-27 at 11 49 56 am](https://user-images.githubusercontent.com/6633715/46161768-0ad78680-c24c-11e8-94af-c53c30fd19f6.png)
![screen shot 2018-09-27 at 11 50 04 am](https://user-images.githubusercontent.com/6633715/46161765-0ad78680-c24c-11e8-8638-8069826ef420.png)

**Comment by woyteck1** [comment]
Hi. I've had the same problem, so I fixed it. Forked from this repo: 
https://github.com/woyteck1/zabbix-template-freenas11

Please try and let me know if it works for you.

**Comment by pgsengstock** [comment]
No luck, unfortunately.  Seems like the allocation unit sizes are off for some of my datasets.  Better overall results than the original template, but still not perfect.  I'm bad with MIBs, but I'll see if I can narrow down where the math is off.

**Comment by fraenki** [comment]
Was anyone able to properly fix this issue? :)

**Comment by pgsengstock** [comment]
No, unfortunately.

**Comment by TidalWave123** [comment]
the developer wrote this on the zabbix site for this template. 

"Please Note: For ZVols, ZPools and Datasets the data is multiplied by 4096 under PreProcessing. This is the AllocationUnits. All of mine were 4096 so decided this is neater. Obviously this can be changed if required, you can get this data from an SNMP Walk. This could be done automatically by creating a item prototype of allocationUnits, another to get the data in units and then another item prototype to to calculate the value in bytes. Instead of 14 item prototypes; there would be 42. If anyone knows of a better way then please let me know."

So I'm trying to figure out how to add the 42 item prototypes but I'm afraid i'm not that well versed in Zabbix. Would anyone be willing to write up a step by step?

**Comment by monotok** [comment]
I haven't looked at this template for years as it was working okay on my system (not huge storage). If you look in the template you should find some other prototypes. I think from memory you'd create two prototypes, each pointing to a different OID and a calculated prototype that multiples the others together. 

Unfortunately I don't have much time to look at this but I have been rebuilding my VM to zabbix 5 so i'll probably look at this template at some point.

**Comment by TidalWave123** [comment]
I got this to work, the values works great on datasets but zpool size seems to be RAW, but it's a good start. 

first thing I did was modify the template to add a prototype item (under discovery rules > dataset). 

I added 
type: SNMP agent
name: datasetAllocationUnits
key: datasetAllocationUnits[{#SNMPVALUE},dunits]
SNMP OID: FREENAS-MIB::datasetAllocationUnits.{#SNMPINDEX}
type: number (unassigned)

second thing I did was remove the preprocessing that was already on the original items, under the preprocessing tab -> remove from all the other item prototypes. 

third thing is to add another calculated item prototype to multiply the allocation units into the total size of the dataset. 

name: ProperSizeofDataset {#SNMPVALUE}
type: calculated
key: vfs.fs.size[{#SNMPVALUE},pdsize]
formula:  last("datasetAllocationUnits[{#SNMPVALUE},dunits]")*last("vfs.fs.size[{#SNMPVALUE}]")
type of info: numeric (float)
UNITS: B

Then I repeated the same steps for the available bits and used bits. Then I remapped the graphs to point to the new calculated items. 

After that I went over to the item prototypes from the zpools and did the same steps from above but used. FREENAS-MIB::zpoolAllocationUnits.{#SNMPINDEX} to create the zpool allocation units. However I think the zpool allocation units processess the RAW data size of the pool - because my tank is 999TB but the total size of the pool is 1.28PB so I think this calculation isn't factoring in the RAID loss. 

I have many extremely large freenas servers. Some are 1.28PB and then others about 500TB, and others various sizes, so and it seems to work best across the datasets more so than the zpool size. I've tested with zabbix 5.0.2 and freenas 11.3 and 12.0.
